name: manage-azure-policy-18ab93ad
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'policies/Restrict_location_of_information_processing,_storage_and_services_0040d2e5-2779-170d-6a2c-1f5fca353335/**'
#      - 'policies/Vulnerability_assessment_should_be_enabled_on_your_Synapse_workspaces_0049a6b3-a662-4f3e-8635-39cf44ace45a/**'
#      - 'policies/Establish_parameters_for_searching_secret_authenticators_and_verifiers_0065241c-72e9-3b2c-556f-75de66332a94/**'
#      - 'policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**'
#      - 'policies/_Preview_Configure_VMSS_created_with_Shared_Image_Gallery_images_to_install_the_Guest_Attestation_extension_009259b0-12e8-42c9-94e7-7af86aa58d13/**'
#      - 'policies/Private_endpoint_connections_on_Batch_accounts_should_be_enabled_009a0c92-f5b4-4776-9b66-4ed2b4775563/**'
#      - 'policies/Integrate_risk_management_process_into_SDLC_00f12b6f-10d7-8117-9577-0f2b76488385/**'
#      - 'policies/View_and_configure_system_diagnostic_data_0123edae-3567-a05a-9b05-b53ebe9d3e7e/**'
#      - 'policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'policies/Configure_App_Service_app_slots_to_use_the_latest_TLS_version_014664e7-e348-41a3-aeb9-566e4ff6a9df/**'
#      - 'policies/Implement_a_threat_awareness_program_015b4935-448a-8684-27c0-d13086356c33/**'
#      - 'policies/Implement_system_boundary_protection_01ae60e2-38bb-0a32-7b20-d3a091423409/**'
#      - 'policies/Authorize_remote_access_to_privileged_commands_01c387ea-383d-4ca9-295a-977fab516b03/**'
#      - 'policies/Configure_a_private_DNS_Zone_ID_for_table_groupID_028bbd88-e9b5-461f-9424-a1b63a7bee1a/**'
#      - 'policies/_Preview_Azure_Security_agent_should_be_installed_on_your_Windows_Arc_machines_0367cfc4-90b3-46ba-a8a6-ddd5d3514878/**'
#      - 'policies/Identify_incident_response_personnel_037c0089-6606-2dab-49ad-437005b5035f/**'
#      - 'policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**'
#      - 'policies/Design_an_access_control_model_03b6427e-6072-4226-4bd9-a410ab65317e/**'
#      - 'policies/Review_access_control_policies_and_procedures_03d550b4-34ee-03f4-515f-f2e2faf7a413/**'
#      - 'policies/Azure_Kubernetes_Service_Private_Clusters_should_be_enabled_040732e8-d947-40b8-95d6-854c95024bf8/**'
#      - 'policies/Create_a_data_inventory_043c1e56-5a16-52f8-6af8-583098ff3e60/**'
#      - 'policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**'
#      - 'policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**'
#      - 'policies/Verify_inaccurate_or_outdated_PII_0461cacd-0b3b-4f66-11c5-81c9b19a3d22/**'
#      - 'policies/Display_an_explicit_logout_message_0471c6b7-1588-701c-2713-1fade73b75f6/**'
#      - 'policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**'
#      - 'policies/Develop_configuration_management_plan_04837a26-2601-1982-3da7-bf463e6408f4/**'
#      - 'policies/Document_and_implement_wireless_access_guidelines_04b3e7f6-4841-888d-4799-cda19a0084f6/**'
#      - 'policies/_Preview_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**'
#      - .github/workflows/manage-azure-policy-18ab93ad.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_18ab93ad}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          policies/Restrict_location_of_information_processing,_storage_and_services_0040d2e5-2779-170d-6a2c-1f5fca353335/**
          policies/Vulnerability_assessment_should_be_enabled_on_your_Synapse_workspaces_0049a6b3-a662-4f3e-8635-39cf44ace45a/**
          policies/Establish_parameters_for_searching_secret_authenticators_and_verifiers_0065241c-72e9-3b2c-556f-75de66332a94/**
          policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**
          policies/_Preview_Configure_VMSS_created_with_Shared_Image_Gallery_images_to_install_the_Guest_Attestation_extension_009259b0-12e8-42c9-94e7-7af86aa58d13/**
          policies/Private_endpoint_connections_on_Batch_accounts_should_be_enabled_009a0c92-f5b4-4776-9b66-4ed2b4775563/**
          policies/Integrate_risk_management_process_into_SDLC_00f12b6f-10d7-8117-9577-0f2b76488385/**
          policies/View_and_configure_system_diagnostic_data_0123edae-3567-a05a-9b05-b53ebe9d3e7e/**
          policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          policies/Configure_App_Service_app_slots_to_use_the_latest_TLS_version_014664e7-e348-41a3-aeb9-566e4ff6a9df/**
          policies/Implement_a_threat_awareness_program_015b4935-448a-8684-27c0-d13086356c33/**
          policies/Implement_system_boundary_protection_01ae60e2-38bb-0a32-7b20-d3a091423409/**
          policies/Authorize_remote_access_to_privileged_commands_01c387ea-383d-4ca9-295a-977fab516b03/**
          policies/Configure_a_private_DNS_Zone_ID_for_table_groupID_028bbd88-e9b5-461f-9424-a1b63a7bee1a/**
          policies/_Preview_Azure_Security_agent_should_be_installed_on_your_Windows_Arc_machines_0367cfc4-90b3-46ba-a8a6-ddd5d3514878/**
          policies/Identify_incident_response_personnel_037c0089-6606-2dab-49ad-437005b5035f/**
          policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**
          policies/Design_an_access_control_model_03b6427e-6072-4226-4bd9-a410ab65317e/**
          policies/Review_access_control_policies_and_procedures_03d550b4-34ee-03f4-515f-f2e2faf7a413/**
          policies/Azure_Kubernetes_Service_Private_Clusters_should_be_enabled_040732e8-d947-40b8-95d6-854c95024bf8/**
          policies/Create_a_data_inventory_043c1e56-5a16-52f8-6af8-583098ff3e60/**
          policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**
          policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**
          policies/Verify_inaccurate_or_outdated_PII_0461cacd-0b3b-4f66-11c5-81c9b19a3d22/**
          policies/Display_an_explicit_logout_message_0471c6b7-1588-701c-2713-1fade73b75f6/**
          policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**
          policies/Develop_configuration_management_plan_04837a26-2601-1982-3da7-bf463e6408f4/**
          policies/Document_and_implement_wireless_access_guidelines_04b3e7f6-4841-888d-4799-cda19a0084f6/**
          policies/_Preview_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**
